name: university_face_auth
description: "A modern university face authentication app"
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Face Detection & Camera
  camera: ^0.10.5+7
  google_ml_kit: ^0.16.3
  image: ^4.1.3
  
  # UI & Animation
  animate_do: ^3.1.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  
  # Utils
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  equatable: ^2.0.5
  logger: ^2.0.2+1
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700